### ISSUE TITLE
不能兼容

### ISSUE THREAD

**Issue by Andy957** [liangjingkanji/Net#108]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp:  5.0.0
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
兼容什么

**Comment by Andy957** [comment]
不好意思，是我描述不到位，我把okhttp升级到5.0.0后出现
D/NET_LOG: com.drake.net.exception.HttpFailureException:

Caused by: java.lang.NoSuchFieldException: No field m in class Ljava/util/LinkedHashMap; (declaration of 'java.util.LinkedHashMap' appears in /apex/com.android.art/javalib/core-oj.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at okhttp3.OkHttpUtils.tags(OkHttpUtils.java:34)
        at com.drake.net.request.RequestExtensionKt.tags(RequestExtension.kt:107)
        at com.drake.net.request.RequestExtensionKt.downloadListeners(RequestExtension.kt:242)
        at com.drake.net.interceptor.NetOkHttpInterceptor.intercept(NetOkHttpInterceptor.kt:61)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205) 
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158) 
        at com.holic.XXX.ui.activity.LoginActivity$initView$1$invokeSuspend$$inlined$Get$default$1.invokeSuspend(NetCoroutine.kt:198) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) 
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by liangjingkanji** [comment]
请问在demo试过吗? 我看okHttp5.0还没有发布, 你版本描述不准确

**Comment by Andy957** [comment]
试过，okhttp的版本是
'com.squareup.okhttp3:okhttp:5.0.0-alpha.10'
 问题不大，我改回到4.10.0了，我关了这个问题

**Comment by liangjingkanji** [comment]
不建议使用大版本的Alpha版本, 如果未来发布Beta版本我会测试发布新版本的, 当然你也可以发起PR适配或者通知我
